<a href="https://colab.research.google.com/github/Yurih1/DataScience/blob/master/Aula23_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
matriz_a = np.array([ [1.0, 2.0, 8.0, 6.0], [3.0, 4.0, 4.0, 2.0] ])
matriz_b = np.array([ [5.0, 6.0, 9.0, 1.0], [7.0, 8.0, 3.0, 5.0] ])
matriz_c = np.zeros((1, 4))

matriz_resultante = np.concatenate( (matriz_a, matriz_b, matriz_c) )
matriz_resultante

array([[1., 2., 8., 6.],
       [3., 4., 4., 2.],
       [5., 6., 9., 1.],
       [7., 8., 3., 5.],
       [0., 0., 0., 0.]])

In [2]:
# Como fazer a transposição de uma matriz

transposta = matriz_resultante.transpose()
transposta


array([[1., 3., 5., 7., 0.],
       [2., 4., 6., 8., 0.],
       [8., 4., 9., 3., 0.],
       [6., 2., 1., 5., 0.]])

In [3]:
# Estatísticas sobre Matrizes
print('Máximo:', transposta.max() )
print('Mínimo:', transposta.min())
print('Soma:', transposta.sum() )
print('Média:', transposta.mean() )
print('Variância:', transposta.var())
print('Desvio Padrão:', transposta.std()) # Standard Deviation
print('Ptp:', transposta.ptp()) # Diferença entre o maior e o menor valor da matriz

Máximo: 9.0
Mínimo: 0.0
Soma: 74.0
Média: 3.7
Variância: 8.309999999999999
Desvio Padrão: 2.882707061079915
Ptp: 9.0


In [ ]:
import numpy as np
from scipy import linalg

In [5]:
A = np.array([[8]])
B = np.array([[4,2],[3,3]])
C = np.array([[1,4,2],[1,3,3],[2,6,1]])

In [8]:
# Calculando os determinantes 
print('Matriz de A\n', A)
print('Determinante de A\n', round(np.linalg.det(A), 2))

print('Matriz de B\n', B)
print('Determinante de B\n', round(np.linalg.det(B), 2))

print('Matriz de C\n', C)
print('Determinante de C\n', round(np.linalg.det(C), 2))

Matriz de A
 [[8]]
Determinante de A
 8.0
Matriz de B
 [[4 2]
 [3 3]]
Determinante de B
 6.0
Matriz de C
 [[1 4 2]
 [1 3 3]
 [2 6 1]]
Determinante de C
 5.0


In [9]:
# A biblioteca scipy tem um conjuto de ferramentas para matemática científica
import numpy as np
from scipy import linalg

In [10]:
matriz = np.array([ [1,2,3], [0,1,4], [0,0,1] ])
matriz

array([[1, 2, 3],
       [0, 1, 4],
       [0, 0, 1]])

In [11]:
# Calculando a inversa dessa matriz
linalg.inv(matriz)

array([[ 1., -2.,  5.],
       [ 0.,  1., -4.],
       [ 0.,  0.,  1.]])

In [14]:
# Sistema Lineares 
A = np.array( [
    [3, 2, -1], 
    [1, 3, 1], 
    [2, 2, -2] ] )
B = np.array( [ 
    [0], 
    [1], 
    [2] ])

A_inversa = linalg.inv(A)
C = A_inversa.dot(B)
C

array([[-1.],
       [ 1.],
       [-1.]])

In [15]:
# Metodo mais sofisticado
A = np.array( [
    [3, 2, -1], 
    [1, 3, 1], 
    [2, 2, -2] ] )
B = np.array( [ 
    [0], 
    [1], 
    [2] ])

# Primeiro
C = np.linalg.solve(A, B)

print(C)

[[-1.]
 [ 1.]
 [-1.]]


Atividade
<li>Qual é a inversa da matriz M?</li>
    <li>Qual é a transposta da matriz M?</li>
    <li>Qual é o determinante da matriz M para a terceira ordem?</li>
    <li>Apresentar para a matriz M: máximo, mínimo, soma, média, variância e desvio padrão</li>
    <li>Apresente os valores da Diagonal Principal da matriz (M)</li>
    <li>Apresente os valores da Diagonal Secundária da matriz (M)</li>
    <li>Apresente o somatório da Diagonal Principal da matriz (M)</li>
    <li>Apresente o somatório da Diagonal Secundária da matriz(M)</li>

In [16]:
M = np.array([
    [1,  2 ,  3, 4 , 5],
    [7, -2 , -3, 2,  9],
    [4,  5,  -3, 3,  9],
    [4,  6,  7,  2, -1],
    [8, -8,  8, -8,  9]
])

In [22]:
#1
np.linalg.inv(M)

array([[-0.11950092,  0.1437093 , -0.04990804,  0.10891286, -0.01531043],
       [-0.07140727, -0.09944326,  0.14072675,  0.04448974,  0.00333052],
       [ 0.10041259, -0.04255108, -0.04125864,  0.02828454,  0.03116767],
       [ 0.14134811,  0.1272307 , -0.13481135,  0.01531043, -0.06924492],
       [ 0.07913705, -0.06521847,  0.08629517, -0.06879753,  0.03842521]])

In [17]:
#2
transp = M.transpose()
transp

array([[ 1,  7,  4,  4,  8],
       [ 2, -2,  5,  6, -8],
       [ 3, -3, -3,  7,  8],
       [ 4,  2,  3,  2, -8],
       [ 5,  9,  9, -1,  9]])

In [23]:
#3
m3 = M[0:3, 0:3]
round(np.linalg.det(m3), 2)


168.0

In [21]:
#4
print('Máximo:', M.max())
print('Mínimo:', M.min())
print('Soma:', M.sum())
print('Média:', M.mean())
print('Variância:', M.var())
print('Desvio Padrão:', M.std())

Máximo: 9
Mínimo: -8
Soma: 73
Média: 2.92
Variância: 22.8736
Desvio Padrão: 4.782635256843239


In [25]:
#5
print(M.diagonal())

[ 1 -2 -3  2  9]


In [27]:
#6

for i in range(len(M)):
  print(M[i][(len(M)-1)-i])

5
2
-3
6
8


In [28]:
#7
sum(M.diagonal())

7

In [29]:
#8
sum(M[i][(len(M)-1)-i] for i in range(len(M)))

18